services:
  - type: web
    name: my-app
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn mi_proyecto.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mi_proyecto.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
