# Generated by Django 5.2 on 2025-04-04 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('ID_Articulo', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Descripcion', models.CharField(max_length=255)),
                ('Cantidad_Stock', models.IntegerField(default=0)),
                ('Unidad_Base', models.CharField(max_length=50)),
                ('Precio_Compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Precio_Base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('IVA', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('Caracteristicas', models.TextField(blank=True, null=True)),
                ('Categoria', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('Proveedor', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('Fecha_Registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artículo del catálogo',
                'verbose_name_plural': 'Artículos del catálogo',
                'db_table': 'Catalogo',
                'ordering': ['Descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En revisión', 'En revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Enviado', 'Enviado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('creado_por', models.CharField(max_length=100)),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribucion.pedido')),
            ],
        ),
    ]
