# Generated by Django 5.2 on 2025-04-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, to='distribucion.pedido'),
        ),
        migrations.AlterModelTable(
            name='itempedido',
            table='item_pedidos',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
    ]
