# Generated by Django 5.2 on 2025-04-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribucion', '0002_alter_itempedido_pedido_alter_itempedido_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catalogo',
            table='catalogo',
        ),
    ]
